packages:
  - contracts
  - frontend

blockExoticSubdeps: false

allowBuilds:
  "@safe-global/safe-smart-account@git+ssh://git@github.com/safe-global/safe-smart-account.git#dc437e8fba8b4805d76bcbd1c668c9fd3d1e83be": true
  bufferutil: true
  esbuild: true
  keccak: true
  protobufjs: true
  secp256k1: true
  unrs-resolver: true
  utf-8-validate: true

overrides:
  forge-std: github:foundry-rs/forge-std#2f05b3001ed9d74b171d17eac80b3765ce186a76
  ds-test: github:dapphub/ds-test#e282159d5170298eb2455a6c05280ab5a73a4ef0
  "@safe-global/safe-smart-account": github:safe-global/safe-smart-account#dc437e8fba8b4805d76bcbd1c668c9fd3d1e83be
