export const dontPressItAbi = [
  {
    type: "function",
    name: "createRoom",
    stateMutability: "nonpayable",
    inputs: [{ name: "maxPlayers", type: "uint8" }],
    outputs: [{ name: "roomId", type: "uint256" }],
  },
  {
    type: "function",
    name: "joinRoom",
    stateMutability: "nonpayable",
    inputs: [{ name: "roomId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "startGame",
    stateMutability: "nonpayable",
    inputs: [{ name: "roomId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "submitChoice",
    stateMutability: "payable",
    inputs: [
      { name: "roomId", type: "uint256" },
      { name: "encryptedChoice", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "finalizeRound",
    stateMutability: "nonpayable",
    inputs: [
      { name: "roomId", type: "uint256" },
      {
        name: "pressCountAttestation",
        type: "tuple",
        components: [
          { name: "handle", type: "bytes32" },
          { name: "value", type: "bytes32" },
        ],
      },
      { name: "pressCountSignatures", type: "bytes[]" },
      {
        name: "winnerAttestation",
        type: "tuple",
        components: [
          { name: "handle", type: "bytes32" },
          { name: "value", type: "bytes32" },
        ],
      },
      { name: "winnerSignatures", type: "bytes[]" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "nextRound",
    stateMutability: "nonpayable",
    inputs: [{ name: "roomId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "expireRound",
    stateMutability: "nonpayable",
    inputs: [{ name: "roomId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "getRoom",
    stateMutability: "view",
    inputs: [{ name: "roomId", type: "uint256" }],
    outputs: [
      { name: "host", type: "address" },
      { name: "players", type: "address[4]" },
      { name: "playerCount", type: "uint8" },
      { name: "maxPlayers", type: "uint8" },
      { name: "round", type: "uint32" },
      { name: "submittedCount", type: "uint8" },
      { name: "pot", type: "uint256" },
      { name: "started", type: "bool" },
      { name: "revealReady", type: "bool" },
      { name: "roundFinalized", type: "bool" },
      { name: "ended", type: "bool" },
      { name: "winner", type: "address" },
    ],
  },
  {
    type: "function",
    name: "getRoundDeadline",
    stateMutability: "view",
    inputs: [{ name: "roomId", type: "uint256" }],
    outputs: [{ name: "", type: "uint64" }],
  },
  {
    type: "function",
    name: "hasSubmitted",
    stateMutability: "view",
    inputs: [
      { name: "roomId", type: "uint256" },
      { name: "player", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "getRoundHandles",
    stateMutability: "view",
    inputs: [{ name: "roomId", type: "uint256" }],
    outputs: [
      { name: "pressCountHandle", type: "bytes32" },
      { name: "winnerIndexHandle", type: "bytes32" },
    ],
  },
  {
    type: "event",
    name: "RoomCreated",
    anonymous: false,
    inputs: [
      { indexed: true, name: "roomId", type: "uint256" },
      { indexed: true, name: "host", type: "address" },
      { indexed: false, name: "maxPlayers", type: "uint8" },
    ],
  },
] as const;
